name: "${NAME}"
main: "${PACKAGE}.HomeManagerPlugin"
version: "${VERSION}"
api-version: "${MCVERSION}"
loader: "${PACKAGE}.HomeManagerLoader"
authors: ["winlogon"]
description: "${DESCRIPTION}"
folia-supported: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
