name: "${NAME}"
main: "${PACKAGE}.HomeManagerPlugin"
version: "${VERSION}"
api-version: "${MCVERSION}"
loader: "${PACKAGE}.HomeManagerLoader"
authors: ["winlogon"]
description: "${DESCRIPTION}"
folia-supported: true

