name: ${NAME}
main: ${PACKAGE}.HomeManagerPlugin
version: ${VERSION}
api-version: ${MCVERSION}
author: winlogon
description: ${DESCRIPTION}
folia-supported: true
commands:
  home:
    description: Base command for /home
    usage: "For a list of commands, type /home help"
